In [2]:
import pandas as pd

df_raw = pd.read_csv(r"squirrels_data/squirrels.csv")
df = df_raw.copy()

In [3]:
df.describe()

                 X            Y          Date  Hectare Squirrel Number
count  3023.000000  3023.000000  3.023000e+03              3023.000000
mean    -73.967184    40.780853  1.011949e+07                 4.123718
std       0.007726     0.010285  4.246671e+04                 3.096492
min     -73.981159    40.764911  1.006202e+07                 1.000000
25%     -73.973102    40.771676  1.008202e+07                 2.000000
50%     -73.968594    40.778166  1.012202e+07                 3.000000
75%     -73.960189    40.791219  1.014202e+07                 6.000000
max     -73.949722    40.800119  1.020202e+07                23.000000

In [4]:
df.head()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Highlight Fur Color,...,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Other Interactions,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9561344937861 40.7940823884086)
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,10192018,4,NaN,NaN,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9688574691102 40.7837825208444)
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,10142018,8,NaN,Gray,NaN,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.97428114848522 40.775533619083)
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Adult,Gray,NaN,...,False,False,False,False,False,False,False,True,NaN,POINT (-73.9596413903948 40.7903128889029)
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Cinnamon,...,False,False,False,False,False,False,False,False,NaN,POINT (-73.9702676472613 40.7762126854894)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3023 entries, 0 to 3022
Data columns (total 31 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   X                                           3023 non-null   float64
 1   Y                                           3023 non-null   float64
 2   Unique Squirrel ID                          3023 non-null   object
 3   Hectare                                     3023 non-null   object
 4   Shift                                       3023 non-null   object
 5   Date                                        3023 non-null   int64
 6   Hectare Squirrel Number                     3023 non-null   int64
 7   Age                                         2902 non-null   object
 8   Primary Fur Color                           2968 non-null   object
 9   Highlight Fur Color                         1937 non-null   object
 10  Combination of Primary and Highlight Color  3023 non-null   object
 11  Color notes                                 182 non-null    object
 12  Location                                    2959 non-null   object
 13  Above Ground Sighter Measurement            2909 non-null   object
 14  Specific Location                           476 non-null    object
 15  Running                                     3023 non-null   bool
 16  Chasing                                     3023 non-null   bool
 17  Climbing                                    3023 non-null   bool
 18  Eating                                      3023 non-null   bool
 19  Foraging                                    3023 non-null   bool
 20  Other Activities                            437 non-null    object
 21  Kuks                                        3023 non-null   bool
 22  Quaas                                       3023 non-null   bool
 23  Moans                                       3023 non-null   bool
 24  Tail flags                                  3023 non-null   bool
 25  Tail twitches                               3023 non-null   bool
 26  Approaches                                  3023 non-null   bool
 27  Indifferent                                 3023 non-null   bool
 28  Runs from                                   3023 non-null   bool
 29  Other Interactions                          240 non-null    object
 30  Lat/Long                                    3023 non-null   object
dtypes: bool(13), float64(2), int64(2), object(14)
memory usage: 463.6+ KB

In [6]:
df.shape

(3023, 31)

In [7]:
def null_percentage(df):
    return (df.isnull().sum() / len(df) * 100).sort_values(ascending=False)

print(null_percentage(df))

Color notes                                   93.979491
Other Interactions                            92.060867
Other Activities                              85.544161
Specific Location                             84.254052
Highlight Fur Color                           35.924578
Age                                            4.002646
Above Ground Sighter Measurement               3.771088
Location                                       2.117102
Primary Fur Color                              1.819385
Hectare Squirrel Number                        0.000000
Date                                           0.000000
Unique Squirrel ID                             0.000000
Y                                              0.000000
Shift                                          0.000000
Hectare                                        0.000000
Combination of Primary and Highlight Color     0.000000
X                                              0.000000
Climbing                                       0.000000
Running                                        0.000000
Eating                                         0.000000
Foraging                                       0.000000
Kuks                                           0.000000
Chasing                                        0.000000
Quaas                                          0.000000
Moans                                          0.000000
Tail twitches                                  0.000000
Tail flags                                     0.000000
Approaches                                     0.000000
Indifferent                                    0.000000
Runs from                                      0.000000
Lat/Long                                       0.000000
dtype: float64

In [8]:
df_no_null = df.drop(columns={'Color notes', 'Other Activities', 'Other Interactions', 'Specific Location','Highlight Fur Color'})

In [9]:
df_no_null.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3023 entries, 0 to 3022
Data columns (total 26 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   X                                           3023 non-null   float64
 1   Y                                           3023 non-null   float64
 2   Unique Squirrel ID                          3023 non-null   object
 3   Hectare                                     3023 non-null   object
 4   Shift                                       3023 non-null   object
 5   Date                                        3023 non-null   int64
 6   Hectare Squirrel Number                     3023 non-null   int64
 7   Age                                         2902 non-null   object
 8   Primary Fur Color                           2968 non-null   object
 9   Combination of Primary and Highlight Color  3023 non-null   object
 10  Location                                    2959 non-null   object
 11  Above Ground Sighter Measurement            2909 non-null   object
 12  Running                                     3023 non-null   bool
 13  Chasing                                     3023 non-null   bool
 14  Climbing                                    3023 non-null   bool
 15  Eating                                      3023 non-null   bool
 16  Foraging                                    3023 non-null   bool
 17  Kuks                                        3023 non-null   bool
 18  Quaas                                       3023 non-null   bool
 19  Moans                                       3023 non-null   bool
 20  Tail flags                                  3023 non-null   bool
 21  Tail twitches                               3023 non-null   bool
 22  Approaches                                  3023 non-null   bool
 23  Indifferent                                 3023 non-null   bool
 24  Runs from                                   3023 non-null   bool
 25  Lat/Long                                    3023 non-null   object
dtypes: bool(13), float64(2), int64(2), object(9)
memory usage: 345.5+ KB

In [10]:
df_no_null.head()

,X,Y,Unique Squirrel ID,Hectare,Shift,Date,Hectare Squirrel Number,Age,Primary Fur Color,Combination of Primary and Highlight Color,...,Foraging,Kuks,Quaas,Moans,Tail flags,Tail twitches,Approaches,Indifferent,Runs from,Lat/Long
0,-73.956134,40.794082,37F-PM-1014-03,37F,PM,10142018,3,NaN,NaN,+,...,False,False,False,False,False,False,False,False,False,POINT (-73.9561344937861 40.7940823884086)
1,-73.968857,40.783783,21B-AM-1019-04,21B,AM,10192018,4,NaN,NaN,+,...,False,False,False,False,False,False,False,False,False,POINT (-73.9688574691102 40.7837825208444)
2,-73.974281,40.775534,11B-PM-1014-08,11B,PM,10142018,8,NaN,Gray,Gray+,...,False,False,False,False,False,False,False,False,False,POINT (-73.97428114848522 40.775533619083)
3,-73.959641,40.790313,32E-PM-1017-14,32E,PM,10172018,14,Adult,Gray,Gray+,...,True,False,False,False,False,False,False,False,True,POINT (-73.9596413903948 40.7903128889029)
4,-73.970268,40.776213,13E-AM-1017-05,13E,AM,10172018,5,Adult,Gray,Gray+Cinnamon,...,True,False,False,False,False,False,False,False,False,POINT (-73.9702676472613 40.7762126854894)

In [11]:
def clean_columns(df):
    df.columns = (
        df.columns
        .str.lower()
        .str.strip()
        .str.replace(r"\s+", "_", regex=True)
    )
    return df
df_cleaned = clean_columns(df_no_null)

In [12]:
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3023 entries, 0 to 3022
Data columns (total 26 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   x                                           3023 non-null   float64
 1   y                                           3023 non-null   float64
 2   unique_squirrel_id                          3023 non-null   object
 3   hectare                                     3023 non-null   object
 4   shift                                       3023 non-null   object
 5   date                                        3023 non-null   int64
 6   hectare_squirrel_number                     3023 non-null   int64
 7   age                                         2902 non-null   object
 8   primary_fur_color                           2968 non-null   object
 9   combination_of_primary_and_highlight_color  3023 non-null   object
 10  location                                    2959 non-null   object
 11  above_ground_sighter_measurement            2909 non-null   object
 12  running                                     3023 non-null   bool
 13  chasing                                     3023 non-null   bool
 14  climbing                                    3023 non-null   bool
 15  eating                                      3023 non-null   bool
 16  foraging                                    3023 non-null   bool
 17  kuks                                        3023 non-null   bool
 18  quaas                                       3023 non-null   bool
 19  moans                                       3023 non-null   bool
 20  tail_flags                                  3023 non-null   bool
 21  tail_twitches                               3023 non-null   bool
 22  approaches                                  3023 non-null   bool
 23  indifferent                                 3023 non-null   bool
 24  runs_from                                   3023 non-null   bool
 25  lat/long                                    3023 non-null   object
dtypes: bool(13), float64(2), int64(2), object(9)
memory usage: 345.5+ KB

In [ ]:
import matplotlib.pyplot as plt

plt.figure(figsize=(20, 8))
plt.scatter(df_cleaned["x"], df_cleaned["y"])

plt.xlabel("x")
plt.ylabel("y")
plt.title("X vs Y")

plt.show()

In [ ]:
df_cleaned['hectare'].unique()

array(['37F', '21B', '11B', '32E', '13E', '11H', '36H', '33F', '21C',
       '11D', '20B', '22F', '36I', '05C', '07H', '16C', '14E', '32A',
       '17F', '16I', '12I', '32F', '25A', '15E', '39G', '29I', '07E',
       '17C', '10A', '28A', '12B', '18A', '33H', '29C', '38C', '31H',
       '08H', '34F', '13H', '35C', '17E', '02B', '19D', '40B', '03E',
       '39C', '06G', '14F', '06I', '15F', '08B', '03A', '05E', '05F',
       '16E', '13F', '29H', '23C', '33C', '38G', '16G', '35A', '28C',
       '32D', '22A', '19C', '15G', '10F', '42E', '22B', '05A', '32H',
       '42C', '41D', '21G', '07F', '38F', '41B', '36A', '31A', '42G',
       '37D', '37E', '24B', '07G', '15I', '19B', '13D', '35B', '40D',
       '38B', '40I', '07B', '40A', '03B', '21D', '10B', '41A', '02F',
       '26A', '35E', '11G', '07A', '03D', '35D', '18G', '06F', '09F',
       '38E', '33G', '32G', '04D', '06H', '15D', '39H', '20F', '09G',
       '05D', '23F', '39A', '13A', '10G', '13C', '32C', '31D', '18C',
       '40E', '04G', '12F', '17H', '03G', '15H', '14G', '42H', '38A',
       '22C', '36F', '05I', '16D', '06D', '12E', '14D', '22D', '08A',
       '02D', '12C', '08F', '02H', '32B', '04E', '14A', '09B', '08C',
       '06B', '39B', '03C', '38D', '10C', '26I', '01B', '09A', '37H',
       '06A', '32I', '02E', '04B', '31F', '23D', '30B', '04F', '33I',
       '37C', '33B', '37I', '37G', '20A', '15A', '16F', '01G', '37B',
       '03I', '12G', '10I', '19H', '34I', '12A', '19F', '20C', '36E',
       '28D', '21E', '39F', '27A', '18D', '27I', '14I', '01H', '30E',
       '16A', '11E', '22I', '41C', '29B', '15B', '18I', '12D', '11F',
       '34D', '20D', '21F', '33D', '08E', '33E', '31G', '02C', '04I',
       '40C', '10H', '30D', '36C', '11I', '01D', '22G', '40G', '01C',
       '07I', '14H', '08I', '13B', '34H', '04A', '42F', '41I', '12H',
       '09C', '36B', '31E', '29D', '42D', '19G', '13I', '24A', '36D',
       '42B', '41E', '18F', '16H', '09D', '07D', '08G', '04C', '23E',
       '30A', '15C', '16B', '11A', '36G', '14C', '21H', '05G', '03F',
       '42I', '14B', '01A', '09I', '18H', '26B', '28I', '01F', '31I',
       '17A', '03H', '02A', '30I', '09E', '39D', '34E', '17D', '21A',
       '13G', '35F', '38I', '09H', '30C', '19E', '08D', '04H', '23B',
       '20G', '17G', '35G', '02I', '10D', '17I', '42A', '34B', '17B',
       '11C', '33A', '31B', '25I', '37A', '01E', '22H', '34A', '19A',
       '06C', '07C', '05B', '23A', '02G', '35H', '06E', '41G', '40H',
       '39I', '23I', '31C', '29A', '22E', '41F', '28B', '35I', '24I',
       '23H', '34C', '39E', '01I', '18E', '27B', '34G', '05H', '40F',
       '30H', '10E', '25B', '20E', '38H', '30F'], dtype=object)

In [ ]:
df_cleaned['primary_fur_color'].unique()

array([nan, 'Gray', 'Cinnamon', 'Black'], dtype=object)

In [ ]:
df_cleaned['running'].unique()

array([False,  True])

In [ ]:
df_cleaned['above_ground_sighter_measurement'].unique()

array([nan, '10', 'FALSE', '30', '6', '24', '8', '25', '5', '50', '4',
       '3', '70', '12', '2', '20', '7', '13', '15', '28', '35', '100',
       '1', '80', '65', '40', '18', '17', '55', '60', '180', '9', '45',
       '0', '43', '16', '33', '11', '23', '31', '14', '19'], dtype=object)

In [ ]:
df_cleaned['above_ground_sighter_measurement'].value_counts()

NameError: name 'df_cleaned' is not defined